version: '3.8'

services:
  pokemon_db:
    image: postgres:14
    container_name: pokemon_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pokemon
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: 
      context: ./backend
    container_name: pokemon_api
    ports:
      - "3001:3001"
    environment:
      - DB_USER=postgres
      - DB_HOST=pokemon_db
      - DB_NAME=pokemon
      - DB_PASSWORD=admin
      - DB_PORT=5432
    volumes:
      - ./backend:/app  
    depends_on:
      - pokemon_db
   
  frontend:
    build:
      context: ./frontend
    container_name: pokemon_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita sobrescribir node_modules en el contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true  # Habilita el hot-reloading en Docker
    depends_on:
      - api
volumes:
  postgres-data: