version: '3.8'  
services:
  pokemon_db: 
    image: postgres:14
    container_name: pokemon_db 
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: pokemon  
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 

volumes:
  postgres-data:  